apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jasm

bases:
  - ../../base

commonLabels:
  environment: prod

images:
  - name: ghcr.io/codnod/jasm
    newName: 581867121223.dkr.ecr.eu-west-1.amazonaws.com/jasm
    newTag: latest

patches:
  - path: deployment-patch.yaml
  - path: service-account-patch.yaml

configMapGenerator:
  - name: jasm-config
    literals:
      - AWS_REGION=eu-west-1
