apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jasm-dev

namePrefix: dev-

bases:
  - ../../base

commonLabels:
  environment: dev

images:
  - name: ghcr.io/codnod/jasm
    newTag: latest

patches:
  - path: deployment-patch.yaml

configMapGenerator:
  - name: jasm-config
    literals:
      - AWS_REGION=us-east-1

secretGenerator:
  - name: aws-credentials
    envs:
      - secrets.env
